#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

go build -C "$SCRIPT_DIR/.." -o "$SCRIPT_DIR/saggy_go"

TESTENV=GOCACHE,XDG_CACHE_HOME,HOME SAGGY="$SCRIPT_DIR/saggy_go" $SCRIPT_DIR/run_test.sh "$@"
